version: "3.7"
services:
  web:
    container_name: candis-webapi
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
    environment:
      - ENV=Development
    volumes:
      - .:/candis_webapi
  mongodb:
    image: mongo
    container_name: candis-mongodb
    ports:
      - 27017:27017
    volumes:
      - .:/data/db
    networks:
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge